[tools]
bun = "1.2.21"
go = "1.25.1"
golangci-lint = "2.5.0"
watchexec = "2.3.2"

[env]
_.path = ['{{config_root}}/browser/node_modules/.bin']

[tasks.setup]
run = ["brew install gpg cloc benbjohnson/litestream/litestream"]

[tasks.dev]
depends = "setup browser-install"
run = "mise browser-watch ::: server-watch"

[tasks.server]
run = ["go run ./cmd/foundation-demo -dev"]
sources = ["**/*.go", "go.mod", "go.sum"]

[tasks.server-watch]
run = ["mise watch --debounce 250ms --exts .go,.json,.sql --restart server"]

[tasks.browser-build]
dir = "browser"
run = "bun run build"

[tasks.browser-watch]
dir = "browser"
run = "bun watch"

[tasks.browser-install]
description = 'Installs dependencies with bun'
dir = 'browser'
run = 'bun install'
sources = ['package.json', 'bun.lock', 'mise.toml']

[tasks.tidy]
run = ["rm go.sum", "go mod tidy"]

[tasks.cloc]
run = "cloc --exclude-dir=node_modules,dist ."

[tasks.lint]
run = "golangci-lint run"
