when:
  - event: push

steps:
  - name: lint
    image: debian:13-slim
    commands:
      - echo "This is the lint step"
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.5.0
      - golangci-lint run
