when:
  - event: push

steps:
  - name: lint and test
    image: gitea.web2.mbertschler.com/docker/woodpecker-ci:latest
    commands:
      # Clean and setup cache directories
      - rm -rf /root/go /root/.local /root/.cache
      - mkdir -p /cache/go /cache/local /cache/cache
      - ln -s /cache/go /root/go
      - ln -s /cache/local /root/.local
      - ln -s /cache/cache /root/.cache
      # Actual lint and test CI steps
      - mise run lint
      - mise run test
